version: '3.4'

services:
  githubactionsreact:
    image: githubactionsreact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
